// Assists in cleaning up the boilerplate README.TXT files generated by VC6.
//
// Accepts one or more dirs as parameters and recursively scans them
// for non-empty "readme.txt" files containing the word "AppWizard".
// Each file's contents are displayed and the user can choose
// to have the contents erased.

var ForReading   = 1;
var ForWriting   = 2;
var ForAppending = 8;

var TristateUseDefault = -2;
var TristateTrue       = -1;
var TristateFalse      =  0;

var fso = new ActiveXObject("Scripting.FileSystemObject");


main();


function main() {
  var args = WScript.Arguments.Unnamed;
  if (args.length == 0) {
    WScript.Echo("ERR: No dirs specified.");
    return;
  }
  for (var n = 0; n < args.length; ++n) {
    try {
      processDir(fso.GetFolder(args(n)));
    }
    catch (x) {
      WScript.Echo('ERR: Cound not process dir "' + args(n) + '": ' + x.description);
    }
  }
}


function processDir(dir) {
  for (var e = new Enumerator(dir.Files); !e.atEnd(); e.moveNext())
    if (e.item().Name.toUpperCase() == "README.TXT")
      processFile(e.item());
  for (var e = new Enumerator(dir.SubFolders); !e.atEnd(); e.moveNext())
    processDir(e.item());
}


function processFile(file) {
  try {
    if (file.Size == 0) return;
    var s = file.OpenAsTextStream(ForReading, TristateUseDefault).ReadAll();
    if (s.indexOf("AppWizard") == -1) return;

    for (var n = 0; n < 100; ++n)
      WScript.Echo();
    WScript.Echo(s);
    WScript.Echo();
    WScript.Echo(file.Path);
    for (;;) {
      WScript.StdOut.Write("Delete file contents? [y/n/q] ");
      var c = WScript.StdIn.ReadLine();
      switch (c.toUpperCase()) {
        case "Y": clearFile(file); return;
        case "N": return;
        case "Q": WScript.Quit(0); return;
      }
    }
  }
  catch (x) {
    WScript.Echo('ERR: Cound not read file "' + file.Path + '": ' + x.description);
  }
}


function clearFile(file) {
  file.OpenAsTextStream(ForWriting);
}


//for /f "usebackq delims=" %f in (`cs "find lame vc6 readmes.js" e:\projects`) do @start notepad "%f"




/*
========================================================================
       WIN32 APPLICATION : tree_tst
========================================================================


AppWizard has created this tree_tst application for you.  

This file contains a summary of what you will find in each of the files that
make up your tree_tst application.

tree_tst.cpp
    This is the main application source file.

tree_tst.dsp
    This file (the project file) contains information at the project level and
    is used to build a single project or subproject. Other users can share the
    project (.dsp) file, but they should export the makefiles locally.
	

/////////////////////////////////////////////////////////////////////////////
Other standard files:

StdAfx.h, StdAfx.cpp
    These files are used to build a precompiled header (PCH) file
    named tree_tst.pch and a precompiled types file named StdAfx.obj.


/////////////////////////////////////////////////////////////////////////////
Other notes:

AppWizard uses "TODO:" to indicate parts of the source code you
should add to or customize.


/////////////////////////////////////////////////////////////////////////////
*/



/*
E:\Projects\-- pending --\-- NEW 1 --\cddb\unicode_console_test\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\CHMdec\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\dirstat\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\dllclass\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\dllclass\dll\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\exercises\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\FileTypeCheck\test\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\FileTypeCheck\test_imglst\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\gfx_8bit_bmp\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\gfx_clr_wheel\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\greeklish\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\image_fx\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\line_morph\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\lv_sort_col_clr\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\mem_bench\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\q2_map_launch\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\reminder\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\splitter\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\storage_test\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\streams\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\sysint_monitor_filter\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\test3\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\test_clsname\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\text_wrap\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\tst_dc\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\tst_lv_align\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\tst_menu\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\tst_riched\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\tst_txtctrl\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\UPXShell\UPXShell\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\UPXShell\UPXShellConfig\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\users_traxx\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\users_traxx\hook\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\win_nudge\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\win_ver\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\wnd_snap\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\wtlTest_1\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\wtl_test\ReadMe.txt
E:\Projects\-- pending --\-- NEW 1 --\xor_test\ReadMe.txt
E:\Projects\audio\mixer\efmixer\ReadMe.txt
E:\Projects\audio\mixer\studio\ReadMe.txt
E:\Projects\audio\mixer_gui\ReadMe.txt
E:\Projects\console\ext_enum_0\list_ext\ReadMe.txt
E:\Projects\console\fontlist\ReadMe.txt
E:\Projects\console\readfile\ReadMe.txt
E:\Projects\controls\editor\ReadMe.txt
E:\Projects\desktop\desktop_patterns\ReadMe.txt
E:\Projects\desktop\SmoothWallpaper\ReadMe.txt
E:\Projects\desktop\SmoothWallpaper\GradientCtrl\ReadMe.txt
E:\Projects\disk\hdd_smart\EFSmart\ReadMe.txt
E:\Projects\disk\hdd_smart\EFSmart\test\ReadMe.txt
E:\Projects\disk\hdd_smart\SMART_info\(hddsmart)\ReadMe.txt
E:\Projects\disk\ntfs_file_streams\alt_file_streams\ReadMe.txt
E:\Projects\disk\OverDisk\overdisk_3\ReadMe.txt
E:\Projects\disk\OverDisk\vc6\ReadMe.txt
E:\Projects\disk\overdisk_5_wtl\guitest\ReadMe.txt
E:\Projects\disk\overdisk_5_wtl\test\ReadMe.txt
E:\Projects\file\BinPatch\testcon\ReadMe.txt
E:\Projects\file\EFRename\EFRename\ReadMe.txt
E:\Projects\file\EFRename\regex_tst\ReadMe.txt
E:\Projects\file\EFRename\tab_theme_bg\ReadMe.txt
E:\Projects\file\filegen\ReadMe.txt
E:\Projects\file\FileSearch\ReadMe.txt
E:\Projects\file\FileTools\ReadMe.txt
E:\Projects\file\file_checks\ReadMe.txt
E:\Projects\file\mht_parser\ReadMe.txt
E:\Projects\file\will_rock_patch_fix\ReadMe.txt
E:\Projects\graphics\ClrPick\conv_test\ReadMe.txt
E:\Projects\graphics\ClrPick\conv_test_gui\ReadMe.txt
E:\Projects\graphics\ClrPick\test_stretchblt\ReadMe.txt
E:\Projects\graphics\colors\ReadMe.txt
E:\Projects\graphics\png_loader\ReadMe.txt
E:\Projects\graphics\ScreenTool\ReadMe.txt
E:\Projects\graphics\test_taskbar_theme\ReadMe.txt
E:\Projects\graphics\test_visual_style\ReadMe.txt
E:\Projects\hex\HexView\ReadMe.txt
E:\Projects\hex\WTLHex\ReadMe.txt
E:\Projects\install\efinstall_cpp\ReadMe.txt
E:\Projects\libs\eflib\experimental\dlgproc\ReadMe.txt
E:\Projects\libs\eflib\experimental\wndproc\ReadMe.txt
E:\Projects\libs\filelib\ReadMe.txt
E:\Projects\libs\my_str_lib\ReadMe.txt
E:\Projects\net\htmlalbum\ReadMe.txt
E:\Projects\pim\namedays\ReadMe.txt
E:\Projects\pim\SmartDateCalc\ReadMe.txt
E:\Projects\shell\DeskLaunch\ReadMe.txt
E:\Projects\shell\DeskPinsVC\dphook\ReadMe.txt
E:\Projects\shell\DeskPinsVC\ico_clr\ReadMe.txt
E:\Projects\shell\DeskPinsVC\str_mask\ReadMe.txt
E:\Projects\shell\DeskPinsVC\test\hit_test_wnd\ReadMe.txt
E:\Projects\shell\desktop_icon_mgr\ReadMe.txt
E:\Projects\shell\desktop_icon_mgr\hook\ReadMe.txt
E:\Projects\shell\EFClock\ReadMe.txt
E:\Projects\shell\EFClock\hook\ReadMe.txt
E:\Projects\shell\EFSysClrs\ReadMe.txt
E:\Projects\shell\hook_test\ReadMe.txt
E:\Projects\shell\hook_test\hook\ReadMe.txt
E:\Projects\shell\spf_menu_fix\ReadMe.txt
E:\Projects\shell\spf_menu_fix\hook\ReadMe.txt
E:\Projects\shell\TaskArrange\loadIconTest\ReadMe.txt
E:\Projects\shell\TaskArrange\MyMsgBox\ReadMe.txt
E:\Projects\shell\TaskArrange\ta_test\ReadMe.txt
E:\Projects\shell\TaskArrange\test\taskbar_msgs\ReadMe.txt
E:\Projects\shell\TaskArrange\test\taskbar_msgs\hook\ReadMe.txt
E:\Projects\shell\workbar\vc\ReadMe.txt
E:\Projects\system\clear_type\ReadMe.txt
E:\Projects\system\clippings\ReadMe.txt
E:\Projects\system\JustRemovePrograms\ReadMe.txt
E:\Projects\system\JustRemovePrograms\RegTest\ReadMe.txt
E:\Projects\system\JustRemovePrograms\RegTest2\ReadMe.txt
E:\Projects\system\MRUEdit\ReadMe.txt
E:\Projects\system\power_buttons\ReadMe.txt
E:\Projects\system\SafePowerKeys\ControlPanel\ReadMe.txt
E:\Projects\system\SafePowerKeys\efpkcfg\ReadMe.txt
E:\Projects\system\suspend_monitor\lvedit_test\ReadMe.txt
E:\Projects\test\_codecvt\ReadMe.txt
E:\Projects\test\_test\conapp\ReadMe.txt
E:\Projects\test\_test\conapp2\ReadMe.txt
E:\Projects\test\_test\winapp\ReadMe.txt
E:\Projects\test_old\antialiased\ReadMe.txt
E:\Projects\test_old\api_impl\ReadMe.txt
E:\Projects\test_old\bool_operator\ReadMe.txt
E:\Projects\test_old\clipbrd_img_catcher\ReadMe.txt
E:\Projects\test_old\CmdLineParser\ReadMe.txt
E:\Projects\test_old\code_bloat\ReadMe.txt
E:\Projects\test_old\cpl_ext\ReadMe.txt
E:\Projects\test_old\cursor\ReadMe.txt
E:\Projects\test_old\desktops\ReadMe.txt
E:\Projects\test_old\dlg_font\ReadMe.txt
E:\Projects\test_old\dll\ReadMe.txt
E:\Projects\test_old\download_mgr\ReadMe.txt
E:\Projects\test_old\dragdrop\ReadMe.txt
E:\Projects\test_old\duffs_device\ReadMe.txt
E:\Projects\test_old\dummy\dll\ReadMe.txt
E:\Projects\test_old\dummyfilegen\ReadMe.txt
E:\Projects\test_old\ext_file_info\ReadMe.txt
E:\Projects\test_old\filelist\ReadMe.txt
E:\Projects\test_old\freedrivespace\ReadMe.txt
E:\Projects\test_old\gridview\ReadMe.txt
E:\Projects\test_old\hard_links\ReadMe.txt
E:\Projects\test_old\hooks\hook\ReadMe.txt
E:\Projects\test_old\icon_hell\ReadMe.txt
E:\Projects\test_old\imgfile_stats\ReadMe.txt
E:\Projects\test_old\jped_load\ReadMe.txt
E:\Projects\test_old\linexpos\ReadMe.txt
E:\Projects\test_old\listview_getstr_speed\ReadMe.txt
E:\Projects\test_old\lv_test\ReadMe.txt
E:\Projects\test_old\multi_subclass_test\ReadMe.txt
E:\Projects\test_old\newfile\ReadMe.txt
E:\Projects\test_old\no_focus2\ReadMe.txt
E:\Projects\test_old\no_focus3\ReadMe.txt
E:\Projects\test_old\opengl_test\ReadMe.txt
E:\Projects\test_old\perf_data\ReadMe.txt
E:\Projects\test_old\perf_timer_test\ReadMe.txt
E:\Projects\test_old\pipes2\child\ReadMe.txt
E:\Projects\test_old\pipes3\client\ReadMe.txt
E:\Projects\test_old\poststats\ReadMe.txt
E:\Projects\test_old\processes\ReadMe.txt
E:\Projects\test_old\richedit\ReadMe.txt
E:\Projects\test_old\section_toolbar\ReadMe.txt
E:\Projects\test_old\ShellMenuDiag\ReadMe.txt
E:\Projects\test_old\static_fx\ReadMe.txt
E:\Projects\test_old\std_handles\ReadMe.txt
E:\Projects\test_old\sticky_wnd\ReadMe.txt
E:\Projects\test_old\stl_speed\ReadMe.txt
E:\Projects\test_old\TaskbarButtons\test\ReadMe.txt
E:\Projects\test_old\templates\ReadMe.txt
E:\Projects\test_old\test_exesize\ReadMe.txt
E:\Projects\test_old\test_libctiny\ReadMe.txt
E:\Projects\test_old\thread_quit_flag\ReadMe.txt
E:\Projects\test_old\tray_icons\hook\ReadMe.txt
E:\Projects\test_old\tree_docview_tst\ReadMe.txt
E:\Projects\test_old\tree_drag\ReadMe.txt
E:\Projects\test_old\tree_tst\ReadMe.txt
E:\Projects\test_old\userinfo\ReadMe.txt
E:\Projects\test_old\vc6_wchar_stream_open\ReadMe.txt
E:\Projects\test_old\winlib\ReadMe.txt
E:\Projects\test_old\win_lib\ReadMe.txt
E:\Projects\test_old\wndproc_obj\ReadMe.txt
E:\Projects\test_old\wnd_monitor\ReadMe.txt
E:\Projects\text\EFText\fonts_enum\ReadMe.txt
E:\Projects\text\EFText\herecomesthepain\ReadMe.txt
E:\Projects\text\EFText\test\ReadMe.txt
E:\Projects\text\nfoview\ReadMe.txt
E:\Projects\text\texter\ReadMe.txt
E:\Projects\text\TextFoo\ReadMe.txt
E:\Projects\trainers\PolylexEnhancer\hook\ReadMe.txt
*/